on: [push, pull_request]
name: Continuous Integration

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os.runner }}
    env:
      PROJECT_NAME: Mediapipe.Net.Runtime
      NET_ENV: net6.0
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: Windows
            runner: windows-latest
          - name: Linux_CPU
            runner: ubuntu-latest
          - name: Linux_GPU
            runner: ubuntu-latest
          - name: MacOS
            runner: macOS-latest
    steps:
      - name: Cache Bazel directory
        uses: actions/cache@v2
        if: ${{ always() }}
        env:
          cache-name: bazel-cache
        with:
          path: ~/.cache/bazel
          key: ${{ matrix.os.name }}-${{ env.cache-name }}-dev

      - name: Cache build directory
        uses: actions/cache@v2
        env:
          cache-name: build-cache
        with:
          path: build
          key: ${{ matrix.os.name }}-${{ env.cache-name }}-dev

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup MinGW (Windows)
        if: ${{ matrix.os.name == 'Windows' }}
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: Setup EGL (Linux, GPU)
        if: ${{ matrix.os.name == 'Linux_GPU' }}
        run: sudo apt install libglfw3-dev libgles2-mesa-dev

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          architecture: "x64"

      - name: Install Numpy
        run: pip install numpy

      - name: Build C# Protobuf sources (Linux, CPU)
        if: ${{ matrix.os.name == 'Linux_CPU' }}
        run: python build.py build --no-install --protobuf -vv

      - name: Build Native Library (*nix, CPU)
        if: ${{ matrix.os.name != 'Windows' && matrix.os.name != 'Linux_GPU' }}
        run: python build.py build --no-install --no-protobuf --desktop cpu --opencv cmake -vv

      - name: Build Native Library (Linux, GPU)
        if: ${{ matrix.os.name == 'Linux_GPU' }}
        run: python build.py build --no-install --no-protobuf --desktop gpu --opencv cmake -vv

      - name: Build Native Library (Windows, CPU)
        if: ${{ matrix.os.name == 'Windows' }}
        run: |
          echo "Setting PYTHON_BIN_PATH to python in PATH"
          $env:PYTHON_BIN_PATH=(Get-Command python).Path
          echo $env:PYTHON_BIN_PATH
          python build.py build --no-install --no-protobuf --desktop cpu --opencv cmake -vv

      - name: Upload Build Artifacts (${{ matrix.os.name }})
        uses: actions/upload-artifact@v2
        with:
          name: Build.${{ matrix.os.name }}
          path: build/
